### ISSUE TITLE
Support alternative registries in micropip

### ISSUE THREAD

**Issue by rth** [pyodide/micropip#7]
We have discussed this from time to time, but I can't find an issue about it.

It would be good to support alternative registries in micropip. We already support installation from custom URLs, however, a registry that supports the wheelhouse JSON protocol (compatible wirth PyPi) would be much faster and more convenient to use for dependency resolution.

Maybe this would be a global setting,
```py
micropip.set_registry('"https://some-registory.com/endpoint/")
```
with the default being `https://pypi.org/pypi/`. The only place it's used [is here](https://github.com/pyodide/pyodide/blob/main/packages/micropip/src/micropip/_micropip.py#L85).

Alternatively, we could support a list of channels ordered by priority. That would be maybe better but a bit more difficult to implement correctly.

**Comment by pradyunsg** [comment]
This should probably be accompanied by switching to using the intended-for-installers Simple API (https://pypi.org/simple/httpx/) via https://pypi.org/project/mousebender/, and moving away from using the PyPI's (non-standardised) JSON API entirely.

In theory, using mousebender directly would mean that you can eventually (gracefully) start using the nicer JSON-based simple API (https://pypi.org/simple/httpx/?format=application/vnd.pypi.simple.v1+json) as well while maintaining near complete compatibility with the older index formats.

FWIW, the plan is for pip to migrate to something like mousebender at some point in the future. Here's what pip's logic for parsing looks like (it'll seem relatively complicated, due to mix of historical reasons for what this code needs to do there): https://github.com/pypa/pip/blob/0a21080411c25acfb87fbc380631806e0477d7d3/src/pip/_internal/index/collector.py#L229

**Comment by rth** [comment]
Thanks for the additional context!  

Do you know plan if external wheel storing solutions (e.g. Artifactory, Github Packages etc) plan to support this newer Simple API? Because the goal is also to make this work with alternative registries with which pip currently works. And the alternative registry is likely not going to be PyPI.

**Comment by pradyunsg** [comment]
The simple API is what all package indexes implement (Artifactory, devpi etc) and it is what pip uses.

If you want relevant PEP numbers, see https://packaging.python.org/en/latest/specifications/simple-repository-api/. That doesn't mention PEP 691 yet, but that's implemented on PyPI too.

**Comment by hoodmane** [comment]
Unfortunately I think PyPI still hasn't implemented PEP 658 which would allow the biggest improvement.

One benefit of using the simple api is that we already produce it for our own packages as part of the venv code.

**Comment by pradyunsg** [comment]
You don’t need PEP 658, if all you’re doing is operate with wheels — you can download them and look at their metadata to find the right things out.

**Comment by pradyunsg** [comment]
I’ll try to find some time to put together a PoC for this — it isn’t a lot of complexity, if you have a piece to fetch a zip file and a way to read within it.

**Comment by hoodmane** [comment]
> You don’t need PEP 658, if all you’re doing is operate with wheels — you can download them and look at their metadata to find the right things out.

Sometimes after looking at the metadata it turns out it is the wrong wheel though. Would be nice to be able to see metadata before downloading the wheel. In no case is pep 658 *necessary* but it is a big improvement.

**Comment by pradyunsg** [comment]
My understanding is that micropip isn’t doing backtracking dependency resolution, correct? If all you need is things like requires-python and yanking information, that’d available in the simple api responses as is.

**Comment by hoodmane** [comment]
1. With the metadata we could download all wheels at the same time, instead we have to download them sequentially
2. With the metadata if we fail to resolve dependencies we could give up before downloading anything, instead we have to download a bunch of wheels before realizing there is a problem and throwing them away

**Comment by pradyunsg** [comment]
and... yes, having metadata available statically is good, I'm aware of that. I agree that PEP 658 is an improvement for installers (there's a reason we worked on that standardisation effort, and why implementing this within pip eagerly was something I worked toward).

At the end of the day, there is no guarentee that PEP 658 is going to be implemented by alternative indexes or even that all the wheels in the index will have had their metadata extracted+presented via those mechanisms. The degraded experience from your comment above is the behaviour of pip today and, arguably, is better than not being able to use pyodide with an alternative index *at all*.

PEP 658 is an improvement, yes, but it's not a requirement and neither is it guarenteed to be supported. It's similar to PyPI JSON API's dependency information in some senses, except that it's much more likely that you see PEP 658 implemented by folks like Artifactory and devpi in the future, rather than the PyPI `/json` endpoints; and it's reliable data with clearer semantics associated with it.

I'm gonna step away from this now -- I'm really not interested in being told about how/why static metadata for dependency resolution is useful.

**Comment by hoodmane** [comment]
Sorry I didn't mean to be rude. As you say, pep 658 or no this is a good proposal. I am in favor of it. I think I agree with you about everything. the situation with metadata is so frustrating that I tend to gripe about it at every opportunity. But it's not really that relevant.

**Comment by rth** [comment]
Yes, we really appreciate your thoughts on this @pradyunsg , thanks again!

**Comment by pradyunsg** [comment]
> Sorry I didn't mean to be rude.

You weren't. :)

You caught me at the end of a slightly frustrating day and I was trying to avoid directing/venting that frustration onto you, somewhat unsuccessfully in hindsight -- sorry about that!
